### ISSUE TITLE
Stack Overflow question/example

### ISSUE THREAD

**Issue by bbolker** [jvparidon/lmerMultiMember#58]
Someone asked a [multi-membership model question on SO](https://stackoverflow.com/questions/77303719/lmer-glmer-how-to-generate-random-effects-design-matrix). I took a *very* brief shot at using `lmerMultiMember` to answer it, but failed, so I fell back on the hacky way I've illustrated elsewhere. Feel free to post an answer there that uses the package ...

**Comment by jvparidon** [comment]
Hi Ben, thanks for pointing this out!

The only reason your example `lmerMultiMember` code doesn't work is that you don't pass the dataframe `df` in through the `data` arg of the `lmer()` call. `lmerMultiMember` can't handle this because the way it handles missing cases requires a dataframe for the "dense" data and a sparse matrices for the multiple membership data. I can't comment or edit on SO because I don't have enough reputation, so I posted an additional answer explaining this, I hope you or someone else can merge it into your answer for clarity.

**Comment by bbolker** [comment]
Maybe add a check/informative error message if `data` is NULL/missing?
